# Generated by Django 5.1.4 on 2025-03-05 07:03

import adl_adcon_db_plugin.validators
import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_alter_networkconnection_plugin_processing_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADCONDBConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('db_host', models.CharField(max_length=255, verbose_name='Database Host')),
                ('db_port', models.PositiveIntegerField(verbose_name='Database Port')),
                ('db_name', models.CharField(max_length=255, verbose_name='Database Name')),
                ('db_user', models.CharField(max_length=255, verbose_name='Database User')),
            ],
            options={
                'verbose_name': 'ADCON Database Connection',
                'verbose_name_plural': 'ADCON Database Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='ADCONStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('adcon_station_id', models.PositiveIntegerField(verbose_name='ADCON Station ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone')),
                ('start_date', models.DateTimeField(blank=True, help_text='Start date for data pulling. Select a past date to include the historical data. Leave blank for collecting realtime data only', null=True, validators=[adl_adcon_db_plugin.validators.validate_start_date], verbose_name='Start Date')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='ADCONStationVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adcon_parameter_id', models.PositiveIntegerField(unique=True, verbose_name='ADCON Parameter ID')),
                ('adcon_parameter_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='ADCON Parameter Unit')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('station_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_adcon_db_plugin.adconstationlink')),
            ],
        ),
    ]
