# Generated by Django 5.1.4 on 2025-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_adcon_db_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcondbconnection',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Database Password'),
        ),
    ]
