# Generated by Django 5.1.4 on 2025-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_adcon_db_plugin', '0002_adcondbconnection_db_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcondbconnection',
            name='only_stations_with_coords',
            field=models.BooleanField(default=False, verbose_name='List Only Stations with Coordinates'),
        ),
        migrations.AlterField(
            model_name='adconstationlink',
            name='adcon_station_id',
            field=models.PositiveIntegerField(help_text='Select an ADCON Station ID', verbose_name='ADCON Station ID'),
        ),
    ]
