# Generated by Django 5.1.4 on 2025-04-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_adcon_db_plugin', '0003_adcondbconnection_only_stations_with_coords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adconstationlink',
            options={'verbose_name': 'ADCON Station Link', 'verbose_name_plural': 'ADCON Station Links'},
        ),
    ]
