# Generated by Django 5.1.9 on 2025-08-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_adcon_db_plugin', '0004_alter_adconstationlink_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adconstationlink',
            name='timezone',
        ),
    ]
