# Generated by Django 5.1.9 on 2025-09-10 18:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_adcon_db_plugin', '0005_remove_adconstationlink_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adconstationvariablemapping',
            name='station_link',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_adcon_db_plugin.adconstationlink'),
        ),
    ]
