# Generated by Django 6.0.7 on 2026-08-19 15:44

import adl_adcon_db_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_adcon_db_plugin', '0006_alter_adconstationvariablemapping_station_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adconstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Collection never starts before this date. On the first run it is the start of the backfill; afterwards, moving it forward past the latest saved record skips the gap. Leave empty to start from the last hour.', null=True, validators=[adl_adcon_db_plugin.validators.validate_start_date], verbose_name='Collection Start Date'),
        ),
    ]
